import { Offer, OfferStatus, OfferLineItem } from '@/types';

export const mockOffers: Offer[] = [
  {
    id: 'OFF-001',
    offerNumber: 'LOR-2024-001',
    customerId: 'CUS-001',
    customerName: 'TAHSEEL Information Technology',
    date: '2024-09-15',
    validUntil: '2024-10-15',
    lineItems: [
      {
        id: 'LI-001',
        serviceId: 'SRV-005',
        description: 'Logo Design - Complete logo design with 3 concepts, revisions, and final files',
        quantity: 1,
        unitPrice: 5000,
        total: 5000,
      },
      {
        id: 'LI-002',
        serviceId: 'SRV-006',
        description: 'Brand Identity Package - Full brand identity: logo, colors, typography, brand guidelines',
        quantity: 1,
        unitPrice: 15000,
        total: 15000,
      },
      {
        id: 'LI-003',
        serviceId: 'SRV-008',
        description: 'Stationery Design - Business cards, letterhead, envelope, email signature',
        quantity: 1,
        unitPrice: 2500,
        total: 2500,
      },
    ],
    subtotal: 22500,
    vatRate: 5,
    vatAmount: 1125,
    total: 23625,
    terms: 'Payment: 50% upon acceptance, 50% upon delivery\nDelivery: 6-8 weeks from project start\nIncludes: 3 rounds of revisions per deliverable',
    status: 'accepted',
    notes: 'Client approved via email on 2024-09-20',
    // Internal cost data (from estimator)
    laborCost: 12000,
    overheadPercent: 15,
    overheadAmount: 1800,
    profitAmount: 9825,
  },
  {
    id: 'OFF-002',
    offerNumber: 'LOR-2024-002',
    customerId: 'CUS-003',
    customerName: 'Al Majaz Waterfront',
    date: '2024-10-25',
    validUntil: '2024-11-25',
    lineItems: [
      {
        id: 'LI-004',
        serviceId: 'SRV-004',
        description: 'Social Media Campaign - New Year celebration campaign',
        quantity: 1,
        unitPrice: 3500,
        total: 3500,
      },
      {
        id: 'LI-005',
        serviceId: 'SRV-011',
        description: 'Social Media Video (15-30s) - Countdown video',
        quantity: 2,
        unitPrice: 3000,
        total: 6000,
      },
      {
        id: 'LI-006',
        description: 'Event photography coverage (additional)',
        quantity: 1,
        unitPrice: 5000,
        total: 5000,
      },
    ],
    subtotal: 14500,
    vatRate: 5,
    vatAmount: 725,
    total: 15225,
    terms: 'Payment: 100% upon completion\nDelivery: By November 30, 2024',
    status: 'accepted',
  },
  {
    id: 'OFF-003',
    offerNumber: 'LOR-2024-003',
    customerId: 'CUS-008',
    customerName: 'Al Zarooni Group',
    date: '2024-10-28',
    validUntil: '2024-11-28',
    lineItems: [
      {
        id: 'LI-007',
        serviceId: 'SRV-005',
        description: 'Logo Design - Development project branding',
        quantity: 1,
        unitPrice: 8000,
        total: 8000,
      },
      {
        id: 'LI-008',
        serviceId: 'SRV-006',
        description: 'Brand Identity Package - Complete visual identity',
        quantity: 1,
        unitPrice: 20000,
        total: 20000,
      },
      {
        id: 'LI-009',
        serviceId: 'SRV-013',
        description: 'Brochure Design (Tri-fold) - Sales brochure',
        quantity: 2,
        unitPrice: 2000,
        total: 4000,
      },
      {
        id: 'LI-010',
        serviceId: 'SRV-014',
        description: 'Company Profile (20 pages) - Project profile',
        quantity: 1,
        unitPrice: 12000,
        total: 12000,
      },
      {
        id: 'LI-011',
        serviceId: 'SRV-023',
        description: 'Signage Design - Sales center signage',
        quantity: 1,
        unitPrice: 8000,
        total: 8000,
      },
    ],
    subtotal: 52000,
    vatRate: 5,
    vatAmount: 2600,
    total: 54600,
    terms: 'Payment: 30% deposit, 40% midway, 30% upon completion\nDelivery: 10-12 weeks',
    status: 'accepted',
    notes: 'Premium client - priority handling',
  },
  {
    id: 'OFF-004',
    offerNumber: 'LOR-2024-004',
    customerId: 'CUS-007',
    customerName: 'Sharjah Art Foundation',
    date: '2024-11-05',
    validUntil: '2024-12-05',
    lineItems: [
      {
        id: 'LI-012',
        serviceId: 'SRV-024',
        description: 'Exhibition Stand Design - 3D visualization included',
        quantity: 1,
        unitPrice: 15000,
        total: 15000,
      },
      {
        id: 'LI-013',
        serviceId: 'SRV-017',
        description: 'Magazine/Catalogue Design - Exhibition catalogue (80 pages)',
        quantity: 1,
        unitPrice: 25000,
        total: 25000,
      },
      {
        id: 'LI-014',
        serviceId: 'SRV-023',
        description: 'Signage Design - Wayfinding system',
        quantity: 1,
        unitPrice: 8000,
        total: 8000,
      },
    ],
    subtotal: 48000,
    vatRate: 5,
    vatAmount: 2400,
    total: 50400,
    terms: 'Payment: 50% upon acceptance, 50% upon delivery\nDelivery: By January 15, 2025',
    status: 'sent',
    notes: 'Awaiting client approval - follow up next week',
  },
  {
    id: 'OFF-005',
    offerNumber: 'LOR-2024-005',
    customerId: 'CUS-005',
    customerName: 'Bee\'ah',
    date: '2024-07-20',
    validUntil: '2024-08-20',
    lineItems: [
      {
        id: 'LI-015',
        serviceId: 'SRV-012',
        description: 'Corporate Video (2-3 min) - Sustainability video',
        quantity: 1,
        unitPrice: 35000,
        total: 35000,
      },
      {
        id: 'LI-016',
        serviceId: 'SRV-010',
        description: 'Explainer Video (60s) - Social media cut',
        quantity: 1,
        unitPrice: 10000,
        total: 10000,
      },
    ],
    subtotal: 45000,
    vatRate: 5,
    vatAmount: 2250,
    total: 47250,
    status: 'accepted',
    notes: 'Project on hold per client request',
  },
  {
    id: 'OFF-006',
    offerNumber: 'LOR-2024-006',
    customerId: 'CUS-004',
    customerName: 'Sharjah Chamber of Commerce',
    date: '2024-11-10',
    validUntil: '2024-12-10',
    lineItems: [
      {
        id: 'LI-017',
        serviceId: 'SRV-016',
        description: 'Annual Report Design - 2024 Annual Report with infographics',
        quantity: 1,
        unitPrice: 28000,
        total: 28000,
      },
    ],
    subtotal: 28000,
    vatRate: 5,
    vatAmount: 1400,
    total: 29400,
    status: 'draft',
    notes: 'Pending final scope confirmation',
  },
  {
    id: 'OFF-007',
    offerNumber: 'LOR-2024-007',
    customerId: 'CUS-002',
    customerName: 'Sharjah Economic Development Department (SEDD)',
    date: '2024-08-15',
    validUntil: '2024-09-15',
    lineItems: [
      {
        id: 'LI-018',
        description: 'Website redesign rejected - client went with different vendor',
        quantity: 1,
        unitPrice: 80000,
        total: 80000,
      },
    ],
    subtotal: 80000,
    vatRate: 5,
    vatAmount: 4000,
    total: 84000,
    status: 'rejected',
    notes: 'Lost to competitor - price was the main factor',
  },
];

export const getOfferById = (id: string): Offer | undefined => {
  return mockOffers.find((o) => o.id === id);
};

export const getOffersByCustomer = (customerId: string): Offer[] => {
  return mockOffers.filter((o) => o.customerId === customerId);
};

export const getOffersByStatus = (status: OfferStatus): Offer[] => {
  return mockOffers.filter((o) => o.status === status);
};

export const offerStatusLabels: Record<OfferStatus, string> = {
  draft: 'Draft',
  sent: 'Sent',
  accepted: 'Accepted',
  rejected: 'Rejected',
  expired: 'Expired',
};
